---
- name: Deploy Sheep Project
  hosts: all
  become: yes
  tasks:
    - name: Install software-properties-common
      ansible.builtin.apt:
        name: software-properties-common
        state: present
        allow_unauthenticated: true

    - name: Install dotnet SDK
      ansible.builtin.apt:
        name: dotnet-sdk-9.0
        state: present
        update_cache: yes
        allow_unauthenticated: true
